keieiei/freemarket_sample_47B

Gemfile, Gemfile.lock, config/database.yml, db/schema.rb
Mysql2のgemをインストールした。
今までの環境通りmysql2を使用したいため
=> ChangetoMysql

Gemfile, Gemfile.lock, config/unicorn.rb
=> InstallUnicorn

Capfile, Gemfile, Gemfile.lock, config/deploy.rb, config/deploy/production.rb, config/deploy/staging.rb, config/unicorn.rb
Capistranoインストール、その他設定を行った。
自動デプロイのために必要であるため
=> InstallCapistrano

app/models/user.rb, config/routes.rb, db/migrate/20190609074839_devise_create_users.rb, db/migrate/20190609081406_add_nickname_to_users.rb, db/schema.rb, test/fixtures/users.yml, test/models/user_test.rb
Userモデルを作成した。
メルカリにおいてUserモデルは商品モデルと対をなす最重要モデルであり、他のモデルに先駆けて作成する必要があるから。
=> Userモデルの作成

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_main-page__sell-btn.scss, app/views/shared/main-page/_footer-sell-button.html.haml, app/views/users/index.html.haml
マイページの出品ボタンのマークアップを作成した。
メルカリ基本ビューの1つmain-pageの代表であるマイページのマークアップは他より優先して作成する必要がある。今回は出品ボタンのマークアップを作成した。
=> マイページの出品ボタンのマークアップ

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/mainheader.js, app/assets/stylesheets/modules/_main-page__header__nav-box__right-box__list__item__item-box--mypage.scss, app/assets/stylesheets/modules/_main-page__header__nav-box__right-box__list__item__item-box.scss, app/views/shared/main-page/main-header/mypage/_header.html.haml, app/views/shared/main-page/main-header/notification/_notification.html.haml
マイページのヘッダーで動きのある部分をjQueryにより再現した。
マイページのビューはメルカリ基本ビューmain-pageの代表となるため、他より優先して作成した。
今回はヘッダーの動きのある部分をjQueryで実装した。
=> マイページのヘッダーのjQuery作成

app/assets/javascripts/user.js
マイページのボディ部分のjQueryを作成した。
マイページはメルカリ基本ビューの1つなので、他より優先して作成した。
今回はマイページのボディ部分のjQueryを作成した。
=> マイページのボディ部分のjQuery作成

config/environments/production.rb
assetsコンパイルの設定を変更した。
下記エラー対処のため変更。
ActionView::Template::Error (The asset "recaptcha.jpeg" is not present in the asset pipeline.):
=> Change_Config_Assets

Gemfile, Gemfile.lock
gimeiとphonelibのgemfileを追加した。またgemfileの配置を変更した
ユーザーの新規登録のため、gimeiとphonelibのgemfileが必要であるから。またgemfileのうちtestのみに使用するgemfileの記述箇所を変更した。
=> gimeiとphonelibのgemfile追加及びgemfileの並び順変更

app/models/image.rb, app/models/item.rb, config/locales/ja.yml, spec/factories/images.rb, spec/factories/items.rb, spec/models/image_spec.rb, spec/models/item_spec.rb, spec/spec_helper.rb
item、imageモデルの単体テストを実施した。
モデルの正常動作の確認をするため。
=> Test_item_image_model

app/models/credit_card.rb, app/models/receiver_information.rb, db/migrate/20190630034023_add_family_name_to_users.rb, db/migrate/20190630041926_create_receiver_informations.rb, db/migrate/20190630042508_create_credit_cards.rb, db/schema.rb, test/fixtures/credit_cards.yml, test/fixtures/receiver_informations.yml, test/models/credit_card_test.rb, test/models/receiver_information_test.rb
userモデルのカラムの変更とreceiver_information及びcredit_cardのモデルを追加した。
ユーザーの新規登録に必要なため。
=> userモデルのカラムの変更とreceiver_information及びcredit_cardのモデルの追加

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_main-page__header__nav-box__right-box__list.scss, app/assets/stylesheets/modules/_main-page__header__nav-box__right-box__list__item--login.scss, app/views/items/index.html.haml, app/views/shared/main-page/_footer-sell-button.html.haml, app/views/shared/main-page/_main-header.html.haml, app/views/shared/main-page/main-header/_login-btns.html.haml
トップページのビューを変更し、ログインしていない状態でユーザー新規登録、ログインページに飛べるリンクを貼った
ユーザーの新規登録ページを作成するにあたり、トップページから飛べるようにしておくため
=> トップページのビューの変更

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_main-page__body__content.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__inner.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__inner__content.scss, app/controllers/users_controller.rb, app/views/shared/main-page/main-header/_mypage.html.haml, app/views/users/confirm_sign_out.html.haml, app/views/users/confirm_sign_out/_confirm_sign_out.html.haml, app/views/users/confirm_sign_out/_main-body.html.haml, app/views/users/main-body/_general-list.html.haml, app/views/users/main-body/_setting-list.html.haml, config/routes.rb
ログアウトページを設置した
ユーザー新規登録を実装する際、機能確認のためログアウトできるよう準備する必要があるから
=> ログアウトページの設置

spec/controllers/items_controller_spec.rb
itemコントローラの単体テストを実施した。
itemコントローラの動作を確認するため。
=> Test_ItemContoroller

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_single-page__body__form__group.scss, app/assets/stylesheets/modules/_single-page__body__form__group__select-wrap.scss, app/controllers/credit_cards_controller.rb, app/controllers/receiver_informations_controller.rb, app/views/credit_cards/new.html.haml, app/views/receiver_informations/_new_body.html.haml, app/views/receiver_informations/new.html.haml, config/routes.rb
ユーザー新規登録3ページ目のサーバサイド及びフロントエンドの実装（javascript除く）
ユーザー新規登録をページの順番通りに実装していくため
=> ユーザー新規登録3ページ目作成

app/controllers/credit_cards_controller.rb, spec/controllers/credit_cards_controller_spec.rb, spec/controllers/receiver_informations_controller_spec.rb, spec/controllers/users_registrations_controller_spec.rb
ユーザー新規登録のコントローラのテストを実装
ユーザー新規登録のコントローラが想定通りの動作をするか確認するため
=> ユーザー新規登録コントローラのテスト

app/assets/javascripts/item.js, app/assets/stylesheets/modules/_main-page__body__top-banner__contents.scss, app/assets/stylesheets/modules/_main-page__body__top-banner__contents__container.scss
トップページのトップバナーを手動・自動で動かせるようにした
トップページは大元になるため
=> トップページのトップバナーの動き

config/deploy.rb, config/deploy/production.rb
自動デプロイの設定であるIPアドレスとSSH鍵のパスを変更した。
新規作成したインスタンスに対応させるため。
=> Edit_IP_KEY

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__form.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__form__group.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__form__group__select-wrap.scss, app/controllers/users/registrations_controller.rb, app/models/user.rb, app/views/users/registrations/identification.html.haml, app/views/users/registrations/identification/_identification.html.haml, app/views/users/registrations/identification/_main-body.html.haml, app/views/users/sidebar/_setting-list.html.haml, config/routes.rb
ユーザー本人確認ページを実装した
ユーザーが本人確認用の情報を登録するため
=> ユーザー本人確認ページの実装

app/models/concerns/credit_card_helper.rb, app/models/credit_card.rb, app/validators/credit_card_number_validator.rb, app/validators/credit_card_security_code_validator.rb, app/validators/credit_card_valid_future_validator.rb, app/views/credit_cards/_new_body.html.haml, config/settings.yml
ユーザー新規登録時のクレジットカード登録のコードを修正した。
マイページからのクレジットカード登録のコーディングと統一性を持たせるため。
=> ユーザー新規登録時のクレジットカード登録の修正

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__inner.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__inner__content.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__inner__payment-list.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__inner__payment-list__item.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__inner__payment-list__item__form.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__inner__payment-list__item__form__figure.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__inner__text.scss, app/controllers/credit_cards_controller.rb, app/helpers/application_helper.rb, app/models/user.rb, app/views/credit_cards/index.html.haml, app/views/credit_cards/index/_index.html.haml, app/views/credit_cards/index/_main-body.html.haml, app/views/users/sidebar/_setting-list.html.haml, config/routes.rb
ユーザーがクレジットカードをすでに登録している時の、マイページ上のクレジットカード登録ページを作成した。
ユーザーが登録したクレジットカードを確認し、変更できるようにするため
=> クレジットカード登録ページの作成（クレジットカード登録時）

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__inner__btn-container.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__inner__btn-container__content.scss, app/controllers/credit_cards_controller.rb, app/views/credit_cards/index/_index.html.haml, config/routes.rb
マイページでのクレジットカード登録ページのうち、カード未登録時のビューを作成した。
ユーザーがクレジットカードを未登録時もしくは登録したクレジットカードを破棄した時、このページから登録できるようにするため
=> クレジットカード登録ページの作成（カード未登録時）

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__form.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__form__content.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__form__content__group.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__form__content__group__credit-card-list.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__form__content__group__credit-card-list__item.scss, app/assets/stylesheets/modules/_main-page__body__content__chapter__form__content__group__valid-select-wrap.scss, app/controllers/credit_cards_controller.rb, app/views/credit_cards/add.html.haml, app/views/credit_cards/add/_add.html.haml, app/views/credit_cards/add/_main-body.html.haml, config/routes.rb
クレジットカード登録ページを作成した
ユーザーが登録するクレジットカードを変更できるようにするため
=> クレジット登録ページの作成

app/models/brand.rb, app/models/item.rb, app/models/large_category.rb, app/models/middle_category.rb, app/models/small_category.rb, db/migrate/20190714100655_create_large_categories.rb, db/migrate/20190714100911_create_middle_categories.rb, db/migrate/20190714101044_create_small_categories.rb, db/migrate/20190714101150_create_brands.rb, db/migrate/20190714101426_rename_large_category_column_to_item.rb, db/schema.rb
カテゴリーとブランドのモデルを追加した
商品の一覧ページの作成や商品検索などを実装する下準備のため
=> カテゴリーとブランドモデルの追加

db/migrate/20190719145714_add_column_to_item.rb, db/migrate/20190719153931_add_userid_to_item.rb, db/schema.rb
Itemモデルにseller、buyerカラムを追加した。
##WHY
商品購入機能のために必須であるため。
=> Itemモデルにseller、buyerカラム追加

app/assets/stylesheets/modules/_main-page.scss, app/assets/stylesheets/modules/_main-page__body__side-bar.scss, app/assets/stylesheets/modules/_main-page__header.scss, app/views/shared/main-page/_bread-crumbs.html.haml, app/views/shared/main-page/_main-header.html.haml, app/views/shared/main-page/main-header/_mypage.html.haml
前回cssファイルを修正した際、別ページのviewが崩れてしまったため、修正した
viewページが崩れたままだと先に進めないから
=> viewの崩れを修正

app/models/item.rb, app/models/user.rb, db/migrate/20190720083153_remove_column_from_items.rb, db/migrate/20190720083551_add_column_to_items.rb, db/schema.rb
itemテーブルにbuyer_idとseller_idを追加した
今後商品購入の機能の実装に必要だから
=> itemテーブルにbuyer_idとseller_idの追加

app/models/brand.rb, app/models/brand_large_category.rb, app/models/brand_middle_category.rb, app/models/brand_small_category.rb, app/models/large_category.rb, app/models/middle_category.rb, app/models/small_category.rb, app/validators/brand_large_category_validator.rb, app/validators/brand_middle_category_validator.rb, app/validators/brand_small_category_validator.rb, db/migrate/20190720104716_create_brand_large_categories.rb, db/migrate/20190720104946_create_brand_middle_categories.rb, db/migrate/20190720105026_create_brand_small_categories.rb, db/schema.rb, db/seeds.rb
ブランドとカテゴリー間の関係性を定義するモデルを作成した
ブランド一覧ページからブランドに関連したcategoryの一覧ページに飛ぶため
=> ブランドとカテゴリー間のモデルの作成

app/controllers/concerns/common.rb, app/controllers/middle_categories_controller.rb, app/views/large_categories/show-body/_show-body.html.haml, app/views/middle_categories/show.html.haml
Middle_categoryの商品一覧ページを作成した
ユーザーがMiddle_categoryを絞って商品を探せるようにするため
=> Middle_categoryの商品一覧ページの作成

app/controllers/small_categories_controller.rb, app/views/small_categories/show.html.haml
Small_categoryの商品一覧ページを作成した
ユーザーがsmall_categoryから商品探せるようにするため
=> Small_categoryの商品一覧ページの作成

app/controllers/brands_controller.rb, app/controllers/concerns/common.rb, app/controllers/large_categories_controller.rb, app/controllers/middle_categories_controller.rb, app/controllers/small_categories_controller.rb, app/views/brands/show.html.haml
Brandの商品一覧ページを作成した。
ユーザーがbrandから商品を探せるようにするため
=> Brandの商品一覧ページの作成

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_main-page.scss, app/assets/stylesheets/modules/_main-page__body__category-index.scss, app/views/large_categories/index.html.haml, app/views/large_categories/index/_index-body.html.haml, app/views/shared/main-page/main-header/_category.html.haml
カテゴリー一覧ページを作成した
ユーザーがカテゴリー一覧から各カテゴリーページに飛べるようにするため
=> カテゴリー一覧ページの作成

app/assets/stylesheets/modules/_single-page__body.scss, app/views/items/buy_confirm.html.haml, app/views/items/show/_item.html.haml
##WHAT
商品確認ページの修正をおこなった。
##WHY
商品確認時に必要であるため。
[![Image from Gyazo](https://i.gyazo.com/36fbb8d5eb4ca8eef7ec45b4c401b951.png)](https://gyazo.com/36fbb8d5eb4ca8eef7ec45b4c401b951)
[![Image from Gyazo](https://i.gyazo.com/1b2936196f50ecd9a31d4868114b8d0c.png)](https://gyazo.com/1b2936196f50ecd9a31d4868114b8d0c)
=> Edit buy confirm haml

app/controllers/brand_upper_categories_controller.rb, app/controllers/brands_controller.rb, app/views/brand_upper_categories/show.html.haml, app/views/brand_upper_categories/show/_body.html.haml, app/views/shared/main-page/main-header/_brand.html.haml, config/routes.rb
ブランド一覧ページを作成した
ユーザーがブランド一覧から出品作品を検索できるようにするため
=> ブランド一覧ページの作成

app/assets/stylesheets/modules/_single-page__body.scss, app/views/items/buy_complete.html.haml, app/views/items/buy_confirm.html.haml
##WHAT
購入完了後のページを作成した。
##WHY
購入機能のために必要であるため
[![Image from Gyazo](https://i.gyazo.com/92859a05b5d0c2fcdb0c26ed56463b8b.png)](https://gyazo.com/92859a05b5d0c2fcdb0c26ed56463b8b)[![Image from Gyazo](https://i.gyazo.com/f3b0c600d6de68d4deb9d3d26067e8bc.png)](https://gyazo.com/f3b0c600d6de68d4deb9d3d26067e8bc)
=> Edit buy complete haml

app/validators/brand_small_category_validator.rb, app/validators/brand_validator.rb, db/seeds.rb
##WHAT
Seed実行時に関連するファイルの修正をおこなった。
##WHY
Seed実行時のエラー対応のため
=> Seed実行時のエラー対応

app/assets/javascripts/item_calc.js, app/assets/stylesheets/modules/_single-page__body__form.scss, app/controllers/items_controller.rb, app/models/item.rb, app/views/items/new.html.haml
商品出品のページの作成をした
商品出品時に必要なため
[![Image from Gyazo](https://i.gyazo.com/0f277d1162a5a4439b4d3522397f02ce.png)](https://gyazo.com/0f277d1162a5a4439b4d3522397f02ce)
[![Image from Gyazo](https://i.gyazo.com/38eae9dc1ec1524d9fd7d976dfa4ac07.png)](https://gyazo.com/38eae9dc1ec1524d9fd7d976dfa4ac07)
[![Image from Gyazo](https://i.gyazo.com/786ce4a9e545dfeff7b318f8f1ace1c4.png)](https://gyazo.com/786ce4a9e545dfeff7b318f8f1ace1c4)
[![Image from Gyazo](https://i.gyazo.com/4802206a9dfe1173a6d63924ea60dd56.png)](https://gyazo.com/4802206a9dfe1173a6d63924ea60dd56)
[![Image from Gyazo](https://i.gyazo.com/46785f13986ce21c9cf390cbf4473f55.gif)](https://gyazo.com/46785f13986ce21c9cf390cbf4473f55)
=> Edit new item scss

app/assets/javascripts/item_new_select.js, app/controllers/items_controller.rb, app/views/items/get_item_sizes.json.jbuilder, app/views/items/get_middle_categories.json.jbuilder, app/views/items/get_sizes_brand_allow.json.jbuilder, app/views/items/get_small_categories.json.jbuilder, app/views/items/new.html.haml, config/routes.rb
出品ページでユーザーの選択した値によってカテゴリー、ブランド、サイズのセレクトボックスを表示・非表示するjqueryを実装した。
カテゴリーやブランド、商品サイズについて、それぞれ決められた組み合わせがあり、こちらの想定した組み合わせでユーザーに選択してもらうため
https://gyazo.com/f00405c976a3da24970861afe275add4
https://gyazo.com/9b91e9d92c060ad64030a922f6458b03
=> 出品ページでカテゴリー、ブランド、サイズの動的動作実装

app/controllers/items_controller.rb, app/views/items/edit.html.haml, app/views/items/show/_item-edit.html.haml, config/routes.rb
商品情報編集機能を作成した。
マークアップは、商品出品のものを再利用。
必須の機能であるため
=> Create item edit

app/assets/javascripts/item_new_select.js, app/controllers/items_controller.rb, app/models/brand.rb, app/models/brand_upper_category.rb
商品出品時、ブランド名を入力されたら、その名前が新規か既存かを判定し、新規の場合は登録されるようにした
ユーザーがこれまでにないブランド名でも登録できるようにするため
=> 商品出品で新規ブランド名入力時の登録処理実装

app/controllers/items_controller.rb
商品購入時、item_stateを購入済みに変更する
商品を購入したものと購入されていないものとを区別するため
=> 商品購入時にitem_stateを購入済みに変更する

app/controllers/items_controller.rb, app/views/items/new/_form.html.haml
商品情報更新時に発生するエラー解決の修正を行った。
情報の更新ができず機能として成立していないため
=> 商品情報更新時のエラー問題解決のため
